alias subl="C:\Program Files\Sublime Text 3\subl.exe"
alias subl="C:\Program Files\Sublime Text 3/sublime_text.exe"
alias subl="C:/Program\ Files/Sublime\ Text\ 3/sublime_text.exe"
alias subl="C:/Program\ Files/Sublime\ Text\ 3/sublime_text.exe"
export PATH="$PATH:/c/Python27"